# C:\AI\AI-Company\.streamlit\secrets.toml
[api_keys]
OPENAI_API_KEY=your key
HUGGINGFACEHUB_API_TOKEN=your key
LANGCHAIN_TRACING_V2=true
LANGCHAIN_ENDPOINT=https://api.smith.langchain.com
LANGCHAIN_API_KEY=your key
LANGCHAIN_PROJECT=AI_AGent
LANGSMITH_API_KEY=your key
TAVILY_API_KEY=your key
GOOGLE_API_KEY=your key
PINECONE_API_KEY=your key
ANTHROPIC_API_KEY=your key
UPSTAGE_API_KEY=your key
COHERE_API_KEY=your key
LLAMA_CLOUD_API_KEY=your key
JINA_API_KEY=your key


[database]
user = "your_db_user"
password = "your_db_password"
